### ISSUE TITLE
OML Vocabulary for basic metrology

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/vocabularies#1]
In OML, there should define a domain-specific vocabulary for basic metrology according chapter 1 of the VIM 3rd edition specification: https://jcgm.bipm.org/vim/en/index.html This vocabulary is the basis of the ISO/IEC 80000 collection of metrology standards that include definitions of quantity kinds and units for several domains (e.g., mechanics, thermodynamics, electricity, ...)

It is important to consider previous work regarding metrology modeling; in particular, the extensive coverage of the ISO/IEC 80000 collection of standards in OMG SysML 1.4 and 1.5
made possible thanks to the conceptual model of Quantities, Units, Dimensions and Values (QUDV) in OMG SysML 1.4 & 1.5, Annex E.5; see: https://www.omg.org/spec/SysML/
For an overview of SysML's QUDV, see: https://www.omg.org/cgi-bin/doc?syseng/2014-03-08
Note that although access to this page is restricted to OMG members, this document was cleared for public release.

The following is a proposal for encoding a QUDV-like vocabulary in OML to achieve a reasonable balance between conceptual rigor and practicality.

# [Quantity Kind](https://jcgm.bipm.org/vim/en/1.2.html)

A QuantityKind is an OML scalar property:
  - domain: an open-world OML entity 
  - range: OML scalar datatype.

# [Quantity](https://jcgm.bipm.org/vim/en/1.1.html)

A Quantity is an OML scalar property:
  - domain: a closed-world OML entity
  - range: OML scalar datatype

A Quantity OML scalar property must be defined as a specialization of a QuantityKind OML scalar property.

It is important to emphasize the semantic distinction between QuantityKind in OML and Quantity in OML. Both are OML scalar properties of some OML entities but these OML entities are semantically very different. For a QuantityKind, the domain OML entity must be defined in an open-world terminology graph. This means that additional axioms may be asserted about such an open-world OML entity in other open-world terminology graphs.

In contract, the domain of a Quantity in OML is an OML entity that must be defined in a closed-world terminology graph. This means that this OML entity domain is effectively a singleton type for something. This means that a Quantity in OML cannot be a property of two distinct things.
This is important to convey the intent in metrology in the subtle distinction between quantity kind and quantity.

# [Measurement Unit](https://jcgm.bipm.org/vim/en/1.9.html)

A Measurement Unit is an OML scalar datatype defined as a restriction of another OML scalar datatype. It is strongly encouraged to use `xsd:string` as the parent OML scalar datatype (unless one is specializing another Measurement Unit). 

The rationale for this particular encoding is that the semantics of OWL2-DL was carefully designed to be independent from the datatype map in OWL2-DL; see: https://www.w3.org/TR/owl2-direct-semantics/#Independence_of_the_Direct_Semantics_from_the_Datatype_Map_in_OWL_2_DL_.28Informative.29
 In practice, what this really means is that the semantics of OWL2-DL does not include the semantics of the datatypes per see (e.g., integer arithmetic); rather, the only semantics about datatypes that matters in OWL2-DL is the fact that one can distinguish among datatype values; not about any datatype-specific relations among those values (e.g., `X < Y` where `X` and `Y` are datatype literals). The idea for encoding metrology in OML is to apply the same principle; that is, treat all MeasurementUnits in OML as definitions of an acyclic taxonomy of scalar datatypes.

Although this might seem to be very restrictive, it is instead quite flexible because it allows
specifying outside of OML (and thus outside of OWL2-DL) additional semantics for Measurement Units defined as OML scalar datatypes.

This encoding allows further specialization of MeasurementUnit OML Scalar datatypes for modeling prefixed units.

**Comment by melaasar** [comment]
fixed by PR #9
