### ISSUE TITLE
viewpoint annotations for decorations at various relative locations of an image.

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/vocabularies#28]
## User Story
As a **library author**, I would like **library-specific viewpoint support** so that **I can customize the view of my library types**.

## Detailed Description
Description providing additional details and context.

Based on experimentation with OML Rosetta, Sirius provides support for showing optional decorations on at different locations (north, south, east, west, center and north/west, north/east, south/west, south/east).

Since one could potentially add multiple such decorations on the same library type, it makes sense to add corresponding viewpoint annotation properties, each of which specifies a decoration image to be displayed at the corresponding decoration location.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

## Sub-task List
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by NicolasRouquette** [comment]
Add to http://opencaesar.io/viewpoint:

```

  @rdfs:label "N decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a North decoration."
  annotation property decoration-n

  @rdfs:label "S decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a South decoration."
  annotation property decoration-s
  
  @rdfs:label "E decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as an East decoration."
  annotation property decoration-e

  @rdfs:label "W decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a West decoration."
  annotation property decoration-w
  
  @rdfs:label "C decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a Center decoration."
  annotation property decoration-c
  
  @rdfs:label "NW decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a North-West decoration."
  annotation property decoration-nw

  @rdfs:label "NE decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a North-East decoration."
  annotation property decoration-ne
  
  @rdfs:label "SW decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a South-West decoration."
  annotation property decoration-sw

  @rdfs:label "SE decoration"
  @dc:^description "A property that represents a path to an image for an element in a viewpoint shown as a South-East decoration."
  annotation property decoration-se
```

**Comment by melaasar** [comment]
The viewpoint vocabulary will be removed from core-vocabularies as of 5.0.0. It is not a "core" vocabulary. The vocabulary could be reintroduced in other tool-specific context to control viewpoints.
